from typing import Any

def class_id_wrap(entType): ...

ent_null: Any
ent_assoc: Any
ent_ptable: Any
ent_pbool: Any
ent_pint: Any
ent_preal: Any
ent_fbool: Any
ent_fint: Any
ent_fkey: Any
ent_freal: Any
ent_fstring: Any
ent_root: Any
ent_view: Any
ent_attr: Any
ent_marker: Any
ent_gforce: Any
ent_accgrav: Any
ent_matrix: Any
ent_default: Any
ent_func: Any
ent_acurve: Any
ent_aflags: Any
ent_material: Any
ent_flex_body: Any
ent_contact: Any
ent_animation: Any
ent_arc: Any
ent_vvar: Any
ent_array: Any
ent_astring: Any
ent_asurface: Any
ent_attr_lib: Any
ent_note: Any
ent_axis: Any
ent_beam: Any
ent_blend: Any
ent_box: Any
ent_bushing: Any
ent_fmarker: Any
ent_data: Any
ent_curve: Any
ent_ccurve: Any
ent_chain: Any
ent_ci_container: Any
ent_circle: Any
ent_clearance: Any
ent_collision: Any
ent_color: Any
ent_contour_plot_legend: Any
ent_joint: Any
ent_coupler: Any
ent_csg: Any
ent_cylinder: Any
ent_dac_file: Any
ent_eigen: Any
ent_deform: Any
ent_design_point: Any
ent_diff: Any
ent_edge: Any
ent_ellipse: Any
ent_ellipsoid: Any
ent_expr_func: Any
ent_expression: Any
ent_external: Any
ent_external_system: Any
ent_gcurve: Any
ent_extrusion: Any
ent_face: Any
ent_femdata: Any
ent_fft_window: Any
ent_field: Any
ent_forced_vibration_ani: Any
ent_friction: Any
ent_frustum: Any
ent_gcell: Any
ent_gcon: Any
ent_gcontact: Any
ent_gear: Any
ent_genforce: Any
ent_gi_btn_stack: Any
ent_gi_container: Any
ent_gi_data_table: Any
ent_gi_window: Any
ent_gi_dbox: Any
ent_gi_field: Any
ent_gi_label: Any
ent_gi_menu: Any
ent_gi_menubar: Any
ent_gi_opt_menu: Any
ent_gi_otable: Any
ent_gi_push_btn: Any
ent_gi_radio_box: Any
ent_gi_separator: Any
ent_gi_slider: Any
ent_gi_tab_container: Any
ent_gi_toggl_btn: Any
ent_gi_toolbar: Any
ent_gi_wizard_page: Any
ent_gi_wizard: Any
ent_glink: Any
ent_gpoint: Any
ent_part: Any
ent_grafile: Any
ent_grid: Any
ent_group: Any
ent_gse: Any
ent_gspdp: Any
ent_gstring: Any
ent_hole: Any
ent_image: Any
ent_incident: Any
ent_integer_matrix: Any
ent_jprim: Any
ent_legend: Any
ent_library: Any
ent_linear_results: Any
ent_loop: Any
ent_lse: Any
ent_macro: Any
ent_mbfilter: Any
ent_mck: Any
ent_mea_angle: Any
ent_subplot: Any
ent_plot: Any
ent_mea_display: Any
ent_mea_object: Any
ent_mea_orient: Any
ent_mea_point: Any
ent_mea_pt2pt: Any
ent_mea_query: Any
ent_mea_range: Any
ent_mea_solvcomp: Any
ent_mea_viewcomp: Any
ent_resset: Any
ent_run: Any
ent_mechanism: Any
ent_mforce: Any
ent_modal_energy: Any
ent_modal_energy_data: Any
ent_mode: Any
ent_motion: Any
ent_mrequest: Any
ent_multi_run: Any
ent_nforce: Any
ent_normal_mode_ani: Any
ent_nurb_curve: Any
ent_nurb_surf: Any
ent_object_matrix: Any
ent_objective: Any
ent_opt_const: Any
ent_outline: Any
ent_picture: Any
ent_page: Any
ent_parameter: Any
ent_pcurve: Any
ent_pinput: Any
ent_plane: Any
ent_plane_surf: Any
ent_plate: Any
ent_plugin: Any
ent_ptemplate: Any
ent_plot3d: Any
ent_point_mass: Any
ent_polyline: Any
ent_poutput: Any
ent_pstate: Any
ent_surface: Any
ent_psurface: Any
ent_report: Any
ent_reqfile: Any
ent_request: Any
ent_resfile: Any
ent_revolution: Any
ent_rigid_stress: Any
ent_rpc_file: Any
ent_rsurf: Any
ent_scatter: Any
ent_sensor: Any
ent_sfdisplay: Any
ent_sforce: Any
ent_sheet: Any
ent_shell: Any
ent_sim_pref: Any
ent_sim_script: Any
ent_solid: Any
ent_solid_shell: Any
ent_solvar: Any
ent_spdp: Any
ent_spec_line: Any
ent_sphere: Any
ent_spline: Any
ent_state_matr: Any
ent_string_matrix: Any
ent_subsystem: Any
ent_surf3d: Any
ent_symmetry: Any
ent_tfsiso: Any
ent_thin_shell: Any
ent_time_marker: Any
ent_tire: Any
ent_torus: Any
ent_ucon: Any
ent_udedef: Any
ent_udeinst: Any
ent_vforce: Any
ent_vlayout: Any
ent_vtorque: Any
ent_fe_part: Any
ent_fe_load: Any
ent_section: Any
ent_fe_node: Any
ent_callback: Any
ent_all: Any
ent_gi_gui: Any
ent_adams: Any
ent_rframe: Any
ent_triad: Any
ent_position: Any
ent_graph: Any
ent_force: Any
ent_var: Any
ent_matrix_class: Any
ent_frame_display: Any
ent_body: Any
ent_anim_base: Any
ent_aplotting: Any
ent_gwire: Any
ent_contact_curve: Any
ent_ppforce: Any
ent_feature: Any
ent_contact_solid: Any
ent_constr: Any
ent_hpc: Any
ent_equ: Any
ent_expr_prim: Any
ent_expr_cont: Any
ent_pfile: Any
ent_gsolid: Any
ent_variable: Any
ent_measure: Any
ent_mea_runtime: Any
ent_mea_vector: Any
ent_opt_func: Any
ent_upper_boundary: Any
ent_analysis: Any
TypeMap: Any
ReverseTypeMap: dict
