import collections
from collections.abc import Generator
from typing import Any, ItemsView, Iterable, KeysView, ValuesView
from Part import Part
from Object import Object

class DuplicateNameError(AttributeError): ...
class ObjectCreationFailure(Exception): ...
class InvalidNameError(AttributeError): ...

class AdamsManager(collections.Mapping):
    parent: Any
    managedClass: Any
    def __init__(self, managed_class, parent) -> None: ...
    def set(self, name, **properties): ...
    def iterDBKeys(self) -> Generator[Any, None, None]: ...
    def values_full(self, *args) -> ValuesView[Object]: ...
    def keys_full(self, *args): ...
    def items_full(self, *args): ...
    def iterkeys(self, *args) -> None: ...
    def iteritems(self, *args) -> None: ...
    def itervalues(self, *args) -> None: ...
    def __len__(self, *args): ...
    def __dir__(self, all: bool = ...): ...
    def create(self, **kwargs)->Part: ...
    def items(self) -> ItemsView[str, Object]: ...
    def values(self) -> ValuesView[Object]: ...
    def keys(self) -> KeysView[str]: ...
    def __getitem__(self, name) -> Object: ...
    def __iter__(self, *args) -> Iterable[str]: ...

class SubclassManager(AdamsManager):
    def __init__(self, managedClass, parent) -> None: ...
    def set(self, name, cls, **kwargs): ...
