from typing import Any

def keyToEnt(key): ...
def keyToTypeName(key): ...

motionTypeMap: Any

def keyToMotionTypeName(key): ...
def keyToMatrixTypeName(key): ...

arrayTypeMap: Any

def keyToArrayTypeName(key): ...

jointTypeMap: Any

def keyToJointTypeName(key): ...

jprimTypeMap: Any

def keyToJprimTypeName(key): ...
def keyToSPDPTypeName(key): ...

DVTypeMap: Any

def keyToDesignVariableTypeName(key): ...

SectionTypeMap: Any

def keyToSectionTypeName(key): ...
