"""Single-file symbol table for semantic analysis of Adams CMD files."""

import re
from dataclasses import dataclass

# Matches the first string literal inside an Adams (eval(...)) expression.
# Example: (eval(".model.mass_" // RTOI(i) // ".cm"))
#           ^^^^^^^^^^^^^^^^^^^
# Captures the content of the leading quoted string so we can register it as
# a dynamic name prefix — any reference that starts with this prefix is
# plausibly a name generated by the same eval pattern and should not fire I202.
_EVAL_LITERAL_PREFIX_RE = re.compile(
    r'\(\s*eval\s*\(\s*["\']([^"\']+)["\']',
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Adams built-in symbols
#
# These objects are pre-created by Adams and are never created by a .cmd file,
# so they would otherwise always trigger I202 "unresolved reference".
# ---------------------------------------------------------------------------

# Standard Adams color names (Adams accepts these case-insensitively)
_BUILTIN_COLORS = [
    "RED", "GREEN", "BLUE", "WHITE", "BLACK", "YELLOW",
    "CYAN", "MAGENTA", "ORANGE", "PURPLE", "MAIZE", "BROWN",
    "PINK", "LIME", "NAVY", "TEAL", "MAROON", "OLIVE",
    "GRAY", "GREY", "SILVER", "GOLD", "BEIGE", "IVORY",
    "LAVENDER", "AQUA", "VIOLET", "INDIGO", "TURQUOISE",
]

# Standard Adams view names — only register the canonical ones that are
# unlikely to clash with user-defined object names.  Derived names like
# 'par2', 'par3', 'front2' etc. are omitted because they are common as
# user-defined part names and would cause false W201 diagnostics.
_BUILTIN_VIEWS = [
    "front", "back", "right", "left", "top", "bottom",
    "iso", "isometric", "perspective",
]

# Special Adams reference names
_BUILTIN_MISC = [
    ("SELECT_LIST", "SelectList"),
    ("all",         "All"),
]


@dataclass
class Symbol:
    name: str         # full object path, e.g. ".model.PART_1"
    object_type: str  # e.g. "Marker", "Part", "MECHANISM"
    line: int         # 0-based line where created


class SymbolTable:
    def __init__(self):
        self.symbols = {}          # lower-cased normalised name → Symbol
        self.dynamic_prefixes = [] # lower-cased normalised prefixes from eval expressions

    @staticmethod
    def _normalize(name: str) -> str:
        """Normalise an Adams database path to always start with a leading dot.

        In Adams, 'model' and '.model' refer to the same object — the leading
        dot is just the root separator that Adams adds automatically. Normalising
        both forms to '.name' means that a model created without a leading dot
        can always be found by a reference that uses one, and vice-versa.
        """
        return name if name.startswith('.') else '.' + name

    def register(self, name, object_type, line):
        """Register a newly created object."""
        normalized = self._normalize(name)
        self.symbols[normalized.lower()] = Symbol(normalized, object_type, line)

    def register_dynamic_prefix(self, prefix):
        """Register a name prefix derived from a runtime eval expression.

        When a new_object argument is assigned via (eval(...)), the exact name
        cannot be determined statically.  Storing the leading string literal
        from the eval expression lets the I202 rule suppress false-positive
        unresolved-reference diagnostics for names that plausibly come from
        the same eval pattern (e.g. loop-generated names like .model.mass_1.cm).
        """
        normalized = self._normalize(prefix).lower()
        if normalized not in self.dynamic_prefixes:
            self.dynamic_prefixes.append(normalized)

    def lookup(self, name):
        """Return the Symbol for name, or None if not registered."""
        return self.symbols.get(self._normalize(name).lower())

    def has(self, name):
        """Return True if name has been registered."""
        return self._normalize(name).lower() in self.symbols

    def has_dynamic_prefix_match(self, name):
        """Return True if name starts with any registered dynamic prefix.

        Used by the I202 rule to suppress unresolved-reference diagnostics for
        names that are likely produced by a loop using (eval(...)) expressions.
        """
        normalized = self._normalize(name).lower()
        return any(normalized.startswith(p) for p in self.dynamic_prefixes)


def _populate_builtins(table):
    """Pre-register Adams built-in objects in *table*.

    These objects exist in every Adams model and are never defined by a .cmd
    file.  Without this pre-population they would always trigger I202.
    """
    # ground part — pre-created in every Adams model
    table.register("ground", "Part", -1)

    # Built-in color constants
    for color in _BUILTIN_COLORS:
        table.register(color, "Color", -1)

    # Built-in view names
    for view in _BUILTIN_VIEWS:
        table.register(view, "View", -1)

    # Miscellaneous built-ins
    for name, obj_type in _BUILTIN_MISC:
        table.register(name, obj_type, -1)


def build_symbol_table(statements, schema):
    """Walk parsed statements top-to-bottom and collect created objects.

    Args:
        statements: list of Statement objects from parser.py
        schema: Schema object

    Returns:
        SymbolTable populated with all objects created in the file
    """
    table = SymbolTable()
    _populate_builtins(table)

    for stmt in statements:
        if stmt.is_comment or stmt.is_blank or stmt.is_control_flow:
            continue
        cmd_key = stmt.resolved_command_key or stmt.command_key
        cmd = schema.get_command(cmd_key)
        if not cmd:
            continue
        for arg in stmt.arguments:
            # Resolve abbreviated argument names
            canonical = schema.resolve_argument_name(cmd_key, arg.name)
            arg_def = cmd["args"].get(canonical or arg.name)
            if arg_def and arg_def.get("type") == "new_object":
                val = arg.value
                if val.startswith("(") or "$" in val:
                    # Runtime expression — extract the leading string literal as
                    # a dynamic prefix so I202 can suppress references to names
                    # plausibly produced by the same eval pattern.
                    m = _EVAL_LITERAL_PREFIX_RE.search(val)
                    if m:
                        table.register_dynamic_prefix(m.group(1))
                else:
                    table.register(
                        val,
                        arg_def.get("object_type", "unknown"),
                        arg.name_line,
                    )
    return table
