"""Single-file symbol table for semantic analysis of Adams CMD files."""

import re
from dataclasses import dataclass, field
from typing import List

# Matches the first string literal inside an Adams (eval(...)) expression.
# Example: (eval(".model.mass_" // RTOI(i) // ".cm"))
#           ^^^^^^^^^^^^^^^^^^^
# Captures the content of the leading quoted string so we can register it as
# a dynamic name prefix — any reference that starts with this prefix is
# plausibly a name generated by the same eval pattern and should not fire I202.
_EVAL_LITERAL_PREFIX_RE = re.compile(
    r'\(\s*eval\s*\(\s*["\']([^"\']+)["\']',
    re.IGNORECASE,
)

# Detects whether a value contains an eval() expression.
_EVAL_DETECT_RE = re.compile(r'\beval\s*\(', re.IGNORECASE)

# Matches Adams dot-path object names inside eval() expressions.
# Requires the first segment after the dot to start with a letter or underscore
# to avoid matching numeric literals like the ".0" in "0.6".
_EVAL_OBJECT_NAME_RE = re.compile(r'\.[a-zA-Z_]\w*(?:\.\w+)*')

# Matches a $variable token immediately preceding a dot-path match.
# Used to filter out partial paths that are suffixes of a $var.path token —
# e.g. in "$model.arm1_len", the regex above would match ".arm1_len", but
# the character just before the "." is part of a $variable identifier, so
# it should not be returned as a standalone object name.
_DOLLAR_IDENT_RE = re.compile(r'\$[a-zA-Z_][a-zA-Z0-9_]*$')


def _extract_eval_object_names(value, value_line, value_column):
    """Extract Adams dot-path object names from an eval() expression value.

    Scans *value* (the raw argument string, e.g. ``"(eval(.m.arm_mass * 0.6))"``
    or a compound expression) for dot-path tokens and returns their document
    positions so callers can build navigation links or record references.

    Dot-path matches that are immediately preceded by a ``$identifier`` token
    are skipped — they are suffix-of-a-$variable paths, not standalone names.
    For example, in ``$model.arm1_len``, the regex matches ``.arm1_len`` but
    the preceding characters ``$model`` identify it as a $variable suffix.

    All names are assumed to lie on *value_line* (eval expressions are always
    single-line after the parser joins continuation lines).

    Args:
        value:        Raw argument value string (including the surrounding parens).
        value_line:   0-based document line of the value start.
        value_column: 0-based column of the first character of *value*.

    Returns:
        List of ``(name, line, column, end_column)`` tuples — one per object
        name token found.  Empty list if *value* contains no eval() call or no
        dot-path names.
    """
    if not _EVAL_DETECT_RE.search(value):
        return []
    results = []
    for m in _EVAL_OBJECT_NAME_RE.finditer(value):
        # Skip if the portion of the string before this match ends with a
        # $variable identifier — the match is a suffix of "$var.path", not
        # a standalone Adams object name.
        prefix = value[:m.start()]
        if _DOLLAR_IDENT_RE.search(prefix):
            continue
        name = m.group(0)
        col = value_column + m.start()
        end_col = value_column + m.end()
        results.append((name, value_line, col, end_col))
    return results

# ---------------------------------------------------------------------------
# Adams built-in symbols
#
# These objects are pre-created by Adams and are never created by a .cmd file,
# so they would otherwise always trigger I202 "unresolved reference".
# ---------------------------------------------------------------------------


# Standard Adams color names sourced from afc/mdi/visedit/colors.py.
# Adams accepts these case-insensitively (lookup is normalised to lowercase).
_BUILTIN_COLORS = [
    # --- authoritative list from colors.py ---
    "Aquamarine", "Black", "Blue", "Blue_Gray", "BlueViolet", "Brown",
    "CadetBlue", "ClayRed", "Coral", "CornflowerBlue", "Cyan", "Dark_Gray",
    "DkGreen", "DkOliveGreen", "DkOrchid", "DkSlateBlue", "DkSlateGray",
    "DkTurquoise", "DkYellow", "DkRed", "DimGray", "Firebrick", "ForestGreen",
    "Goldenrod", "Gray", "Green", "GreenYellow", "Khaki", "LtBlue", "LtGray",
    "LtKhaki", "LtMagenta", "LtSteelBlue", "LimeGreen", "Maize", "Marine",
    "Maroon", "Magenta", "MedAquamarine", "MedBlue", "MedForest", "MedGolden",
    "MedOrchid", "MedSeaGray", "MedSlateBlue", "MedSpring", "MedTurquoise",
    "MedViolet", "MidnightBlue", "Navy", "NearRed", "NearWhite", "NiceGreen",
    "Orange", "Orchid", "PaleGreen", "Peach", "Pink", "Plum", "Red", "Salmon",
    "SeaGreen", "Sienna", "Silver", "SkyBlue", "SlateBlue", "SpringGreen",
    "SteelBlue", "Tan", "Thistle", "Turquoise", "Violet", "VioletRed",
    "VlMagenta", "VlGray", "Wheat", "White", "Yellow", "YellowGreen",
    # --- additional names present in older model files ---
    "Purple", "Lime", "Teal", "Olive", "Gold", "Grey", "Beige", "Ivory",
    "Lavender", "Aqua", "Indigo",
]

# Standard Adams view names — only register the canonical ones that are
# unlikely to clash with user-defined object names.  Derived names like
# 'par2', 'par3', 'front2' etc. are omitted because they are common as
# user-defined part names and would cause false W201 diagnostics.
_BUILTIN_VIEWS = [
    "front", "back", "right", "left", "top", "bottom",
    "iso", "isometric", "perspective",
]

# Special Adams reference names
_BUILTIN_MISC = [
    ("SELECT_LIST", "SelectList"),
    ("all",         "All"),
]


@dataclass
class Symbol:
    name: str         # full object path, e.g. ".model.PART_1"
    object_type: str  # e.g. "Marker", "Part", "MECHANISM"
    line: int         # 0-based line where created


@dataclass
class ObjectReference:
    """One reference to an Adams object in a file (existing_object argument value)."""
    name: str         # object path as written (may or may not have leading dot)
    object_type: str  # expected type per schema arg_def (e.g. "Marker")
    line: int         # 0-based line of the value
    column: int       # 0-based column of the value start
    end_column: int   # 0-based column one past the last char of the value


class SymbolTable:
    def __init__(self, macro_registry=None, show_macro_hint=True, ude_registry=None):
        self.symbols = {}          # lower-cased normalised name → Symbol
        self.dynamic_prefixes = []  # lower-cased normalised prefixes from eval expressions
        self.macro_registry = macro_registry  # MacroRegistry | None
        self.show_macro_hint = show_macro_hint  # bool — include hint in E001 message
        self.ude_registry = ude_registry         # UdeRegistry | None
        self.references: List[ObjectReference] = []   # all existing_object arg values
        self._leaf_index = {}      # lowercase leaf name → List[Symbol]

    @staticmethod
    def _normalize(name: str) -> str:
        """Normalise an Adams database path to always start with a leading dot.

        In Adams, 'model' and '.model' refer to the same object — the leading
        dot is just the root separator that Adams adds automatically. Normalising
        both forms to '.name' means that a model created without a leading dot
        can always be found by a reference that uses one, and vice-versa.
        """
        return name if name.startswith('.') else '.' + name

    def register(self, name, object_type, line):
        """Register a newly created object."""
        normalized = self._normalize(name)
        sym = Symbol(normalized, object_type, line)
        self.symbols[normalized.lower()] = sym
        # Also index by leaf name (last dot-separated component) for leaf-name lookups
        leaf = normalized.lower().rsplit('.', 1)[-1]
        # Replace existing entry with the same full name before appending
        self._leaf_index[leaf] = [
            s for s in self._leaf_index.get(leaf, []) if s.name.lower() != normalized.lower()
        ]
        self._leaf_index[leaf].append(sym)

    def register_dynamic_prefix(self, prefix):
        """Register a name prefix derived from a runtime eval expression.

        When a new_object argument is assigned via (eval(...)), the exact name
        cannot be determined statically.  Storing the leading string literal
        from the eval expression lets the I202 rule suppress false-positive
        unresolved-reference diagnostics for names that plausibly come from
        the same eval pattern (e.g. loop-generated names like .model.mass_1.cm).
        """
        normalized = self._normalize(prefix).lower()
        if normalized not in self.dynamic_prefixes:
            self.dynamic_prefixes.append(normalized)

    def lookup(self, name):
        """Return the Symbol for name, or None if not registered."""
        return self.symbols.get(self._normalize(name).lower())

    def has(self, name):
        """Return True if name has been registered."""
        return self._normalize(name).lower() in self.symbols

    def has_dynamic_prefix_match(self, name):
        """Return True if name starts with any registered dynamic prefix.

        Used by the I202 rule to suppress unresolved-reference diagnostics for
        names that are likely produced by a loop using (eval(...)) expressions.
        """
        normalized = self._normalize(name).lower()
        return any(normalized.startswith(p) for p in self.dynamic_prefixes)

    def lookup_by_leaf_name(self, leaf: str) -> List[Symbol]:
        """Return all Symbols whose leaf name matches (case-insensitive).

        The "leaf" is the last dot-separated component of the object path,
        e.g. the leaf of '.model.ground._tmp_ss_fj_mkr_' is '_tmp_ss_fj_mkr_'.
        Useful as a fallback when only the short name is available.
        Builtin symbols (line == -1) are excluded from the results.
        """
        return [
            s for s in self._leaf_index.get(leaf.lower(), [])
            if s.line >= 0
        ]

    def add_reference(self, name, object_type, line, column, end_column):
        """Record a reference to an Adams object (existing_object argument value)."""
        self.references.append(ObjectReference(
            name=name,
            object_type=object_type,
            line=line,
            column=column,
            end_column=end_column,
        ))

    def get_references_by_name(self, name: str) -> List[ObjectReference]:
        """Return all ObjectReferences matching name.

        Uses full-path match first; falls back to leaf-name match when the
        full path is not found (handles cases where a partial name like
        '_tmp_ss_fj_mkr_' was used in the reference instead of the full path).
        """
        normalized = self._normalize(name).lower()
        matches = [
            r for r in self.references
            if self._normalize(r.name).lower() == normalized
        ]
        if matches:
            return matches
        # Leaf fallback: match references whose last path component equals the query leaf.
        #
        # If the QUERY is a full path (has dots), only match stored references that are
        # themselves leaf-only names (e.g. someone wrote just 'MAR_1' without a full path).
        # This prevents '.demo_model.GROUND.MAR_1' from matching '.model_1.ground.MAR_1'
        # just because both share the leaf 'MAR_1'.
        #
        # If the QUERY is already a leaf-only name (no dots), match any stored reference
        # with the same leaf regardless of how it was written.
        leaf = normalized.rsplit('.', 1)[-1]
        query_is_leaf_only = '.' not in normalized.lstrip('.')
        return [
            r for r in self.references
            if self._normalize(r.name).lower().rsplit('.', 1)[-1] == leaf
            and (query_is_leaf_only or '.' not in self._normalize(r.name).lower().lstrip('.'))
        ]


def _populate_builtins(table):
    """Pre-register Adams built-in objects in *table*.

    These objects exist in every Adams model and are never defined by a .cmd
    file.  Without this pre-population they would always trigger I202.
    """
    # ground part — pre-created in every Adams model
    table.register("ground", "Part", -1)

    # Built-in color constants
    for color in _BUILTIN_COLORS:
        table.register(color, "Color", -1)

    # Built-in view names
    for view in _BUILTIN_VIEWS:
        table.register(view, "View", -1)

    # Miscellaneous built-ins
    for name, obj_type in _BUILTIN_MISC:
        table.register(name, obj_type, -1)


def build_symbol_table(statements, schema, macro_registry=None, show_macro_hint=True,
                       ude_registry=None):
    """Walk parsed statements top-to-bottom and collect created objects.

    Args:
        statements: list of Statement objects from parser.py
        schema: Schema object
        macro_registry: optional MacroRegistry for workspace-wide macro lookup
        show_macro_hint: if True, E001 messages include a hint about scanWorkspaceMacros
        ude_registry: optional UdeRegistry for user-defined element lookup

    Returns:
        SymbolTable populated with all objects created in the file
    """
    table = SymbolTable(
        macro_registry=macro_registry, show_macro_hint=show_macro_hint, ude_registry=ude_registry
    )
    _populate_builtins(table)

    for stmt in statements:
        if stmt.is_comment or stmt.is_blank or stmt.is_control_flow:
            continue
        cmd_key = stmt.resolved_command_key or stmt.command_key
        cmd = schema.get_command(cmd_key)
        if not cmd:
            continue
        for arg in stmt.arguments:
            # Resolve abbreviated argument names
            canonical = schema.resolve_argument_name(cmd_key, arg.name)
            arg_def = cmd["args"].get(canonical or arg.name)
            if not arg_def:
                continue
            arg_type = arg_def.get("type")
            val = arg.value
            if arg_type == "new_object":
                if val.startswith("(") or "$" in val:
                    # Runtime expression — extract the leading string literal as
                    # a dynamic prefix so I202 can suppress references to names
                    # plausibly produced by the same eval pattern.
                    m = _EVAL_LITERAL_PREFIX_RE.search(val)
                    if m:
                        table.register_dynamic_prefix(m.group(1))
                else:
                    table.register(
                        val,
                        arg_def.get("object_type", "unknown"),
                        arg.name_line,
                    )
            elif arg_type == "existing_object":
                # Skip array-valued args — individual elements cannot be isolated
                if arg_def.get("array"):
                    continue
                # Skip runtime expressions — handled by the eval pass below
                if "$" in val or val.lower().startswith("(") or "eval(" in val.lower():
                    pass
                else:
                    lookup_val = val.strip('"\'')
                    if lookup_val:
                        table.add_reference(
                            lookup_val,
                            arg_def.get("object_type", ""),
                            arg.value_line,
                            arg.value_column,
                            arg.value_column + len(val),
                        )
            # Extract object names from eval() expressions in any argument type.
            # Adams variables are commonly referenced inside (eval(...)) on real,
            # integer, or function arguments — the schema type provides no hint
            # that an object name is embedded, so we scan all args here.
            if "eval(" in val.lower():
                for e_name, e_line, e_col, e_end_col in _extract_eval_object_names(
                    val, arg.value_line, arg.value_column
                ):
                    table.add_reference(e_name, "", e_line, e_col, e_end_col)
        # -- UDE instance child registration --
        # When 'assembly create instance' or 'ude create instance' is encountered
        # and a ude_registry is present, register {instance_name}.{param_name} as
        # known symbols so that I202 can resolve references to UDE instance children.
        if table.ude_registry and cmd_key in (
            "assembly create instance", "ude create instance"
        ):
            inst_name = None
            def_name = None
            for arg in stmt.arguments:
                canonical = schema.resolve_argument_name(cmd_key, arg.name)
                aname = canonical or arg.name.lower()
                val_stripped = arg.value.strip().strip('"\'')
                if aname == "instance_name":
                    if not val_stripped.startswith('(') and '$' not in val_stripped:
                        inst_name = val_stripped
                elif aname == "definition_name":
                    if not val_stripped.startswith('(') and '$' not in val_stripped:
                        def_name = val_stripped
            if inst_name and def_name:
                ude_def = table.ude_registry.lookup(def_name)
                if ude_def:
                    for param in ude_def.parameters.values():
                        table.register(
                            inst_name + '.' + param.name, "Vvar", stmt.line_start
                        )
    return table
