!USER_ENTERED_COMMAND  custom command
! -----------------------------------------------------------------
! MACRO NAME:  test.mac
! HELP_STRING:  This is a long and helpful description of what this macro does. 
!               It can be as long as you like and should provide enough information 
!               for the user to understand how to use the macro and what it does.  
!                
!               ### And it supports markdown formatting!
!               - Bullet points
!               - **Bold text**
!               - *Italic text*
!               Numbered lists
!               1. First item
!               2. Second item
! AUTHOR:       Ben Thornton (ben.thornton@hexagon.com)
!$param1:t=int:d=100
! The first parameter. Controls the number of iterations.
!$part_name:t=str:d="part"
! The name of the part to create. Used as a prefix for each part in the loop.
!END_OF_PARAMETERS

var set var=$_self.varname str=(eval(db_default(system_defaults, "model")))

var set var=$_self.tmp_int int=$param1



variable set variable_name=$_self.tmpstr string_value=(eval(str_print('Hello!')))


model create model_name="model_1"


for var=$_self.idx_ start_value=1 end_value=10
    var set var=$_self.idx int=(eval(nint($_self.idx_)))
    var set var=$_self.varname str=(eval(str_print("$param1 " // $_self.idx)))
    
    part create rigid_body name_and_position &
        part_name=(eval("$part_name" // $_self.idx))
end

